Repository Uninett/argus-htmx-frontend, pull requests merged in 2024-09, with the labels that each got.

#91 Make theme selectable via dropdown in user menu
  src/argus_htmx/static/styles.css
  src/argus_htmx/templates/htmx/base.html
  src/argus_htmx/templates/htmx/themes/theme_dropdown.html
  src/argus_htmx/templates/htmx/themes/theme_list.html
  src/argus_htmx/themes/urls.py
  src/argus_htmx/themes/views.py
Labels: demo, polish

#92 Use minified HTMX
  docs/development/dependencies.rst
  src/argus_htmx/static/htmx-2.0.2.min.js
  src/argus_htmx/templates/htmx/base.html
  src/argus_htmx/templates/htmx_base.html
Labels: documentation, demo

#87 Show level input with range widget
  src/argus_htmx/incidents/filter.py
  src/argus_htmx/static/styles.css
  src/argus_htmx/templates/htmx/incidents/_incident_filterbox.html
Labels: polish

#98 Give timestamp a minimum width in incident list
  src/argus_htmx/incidents/customization.py
  src/argus_htmx/templates/htmx/incidents/_incident_start_time_header.html
Labels: polish

#106 Improve "how to run argus_htmx" in the readme
  README.rst
Labels: documentation

#119 Fix typos and articles in README
  README.rst
Labels: documentation

#120 Hide source type in source column in incident list
  src/argus_htmx/templates/htmx/incidents/_incident_source.html
Labels: polish

#121 Show full event type name in incident detail
  src/argus_htmx/templates/htmx/incidents/incident_detail.html
Labels: polish

#117 Hide actions column
  src/argus_htmx/settings.py
Labels: demo, polish

#112 Make a column for tickets
  src/argus_htmx/incidents/customization.py
  src/argus_htmx/settings.py
  src/argus_htmx/static/styles.css
  src/argus_htmx/templates/htmx/incidents/_incident_ticket.html
Labels: polish

#118 Prettyprint level
  src/argus_htmx/static/styles.css
  src/argus_htmx/templates/htmx/incidents/_incident_level.html
  src/argus_htmx/templatetags/argus_htmx.py
Labels: demo, polish

#108 Make modal for add/edit ticket url work in details view
  src/argus_htmx/incidents/forms.py
  src/argus_htmx/incidents/urls.py
  src/argus_htmx/incidents/views.py
  src/argus_htmx/templates/htmx/incidents/_incident_ticket_edit_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_ticket_manual_create_modal.html
  src/argus_htmx/templates/htmx/incidents/incident_detail.html
Labels: demo

#129 Show "Ticket" instead of "Acknowledged" in status block of details page
  src/argus_htmx/templates/htmx/incidents/incident_detail.html
Labels: bug, polish, discussion

#130 Open ticket url from details page in new tab
  src/argus_htmx/templates/htmx/incidents/incident_detail.html
Labels: polish

#140 Add dropdown for user to choose datetime format
  src/argus_htmx/context_processors.py
  src/argus_htmx/dateformat/__init__.py
  src/argus_htmx/dateformat/constants.py
  src/argus_htmx/dateformat/urls.py
  src/argus_htmx/dateformat/views.py
  src/argus_htmx/templates/htmx/base.html
  src/argus_htmx/templates/htmx/dateformat/_dateformat_dropdown.html
  src/argus_htmx/templates/htmx/dateformat/_dateformat_list.html
  src/argus_htmx/templates/htmx/incidents/_incident_start_time.html
  src/argus_htmx/templates/htmx/incidents/_incidents_refresh_info.html
  src/argus_htmx/templates/htmx/incidents/incident_detail.html
  src/argus_htmx/urls.py
Labels: polish

#146 Show different "no hits" text for empty db
  src/argus_htmx/templates/htmx/incidents/_incident_table_rows.html
Labels: polish
