Repository Uninett/argus-htmx-frontend, pull requests merged in 2024-08, with the labels that each got.

#54 Improve tailwind install/usage docs slightly
  README.rst
Labels: documentation

#60 Small fixes in TW CSS docs
  README.rst
Labels: documentation

#69 Select-all incidents feature with update menu placeholder
  src/argus_htmx/incidents/customization.py
  src/argus_htmx/static/styles.css
  src/argus_htmx/tailwindtheme/tailwind.config.js
  src/argus_htmx/tailwindtheme/tailwind.config.template.js
  src/argus_htmx/templates/htmx/incidents/_incident_checkbox.html
  src/argus_htmx/templates/htmx/incidents/_incident_filterbox.html
  src/argus_htmx/templates/htmx/incidents/_incident_table.html
  src/argus_htmx/templates/htmx/incidents/_incidents_menubar.html
  src/argus_htmx/templates/htmx/incidents/_incidents_update_menu.html
  src/argus_htmx/templates/htmx/incidents/_selected_incidents_header.html
  src/argus_htmx/templates/htmx/incidents/incident_list.html
Labels: demo

#64 Improve classic details page
  src/argus_htmx/static/styles.css
  src/argus_htmx/templates/htmx/_base_form_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_acknowledge_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_close_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_ticket_autocreate_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_ticket_edit_modal.html
  src/argus_htmx/templates/htmx/incidents/incident_detail.html
Labels: demo

#90 Polish base modals and ack input fields
  src/argus_htmx/static/styles.css
  src/argus_htmx/templates/htmx/_base_form_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_acknowledge_modal.html
Labels: polish
