Repository Uninett/argus-htmx-frontend, pull requests merged in 2024-10, with the labels that each got.

#162 Fix broken layout of bulk modals
  src/argus_htmx/templates/htmx/incidents/_incidents_update_menu.html
Labels: bug

#189 Add datetime format processor to setup examples in README
  README.rst
Labels: bug, documentation

#193 Add closing to div in login template
  src/argus_htmx/templates/registration/login.html
Labels: lint/reformat

#192 Add whitespace after variable in template
  src/argus_htmx/templates/htmx/incidents/incident_detail.html
Labels: lint/reformat

#188 Remove empty class tag
  src/argus_htmx/templates/htmx/incidents/_incident_table.html
Labels: lint/reformat

#185 Use double quotes in tags
  src/argus_htmx/templates/htmx/base.html
  src/argus_htmx/templates/htmx/incidents/_incident_acknowledge_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_close_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_reopen_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_table.html
  src/argus_htmx/templates/htmx/incidents/_incident_table_rows.html
  src/argus_htmx/templates/htmx/incidents/_incident_ticket_autocreate_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_ticket_edit_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_ticket_manual_create_modal.html
  src/argus_htmx/templates/htmx/incidents/_incidents_update_menu.html
  src/argus_htmx/templates/htmx/incidents/incident_detail.html
Labels: lint/reformat

#199 Delete unused incident row template and function
  src/argus_htmx/incidents/views.py
  src/argus_htmx/templates/htmx/incidents/_incident_row.html
Labels: cleanup

#187 Add names to endblocks
  src/argus_htmx/templates/htmx/base.html
  src/argus_htmx/templates/htmx_base.html
Labels: lint/reformat

#182 Format codebase using djLint
  src/argus_htmx/templates/htmx/_base_form_modal.html
  src/argus_htmx/templates/htmx/base.html
  src/argus_htmx/templates/htmx/dateformat/_dateformat_dropdown.html
  src/argus_htmx/templates/htmx/dateformat/_dateformat_list.html
  src/argus_htmx/templates/htmx/incidents/_base_incident_update_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_ack.html
  src/argus_htmx/templates/htmx/incidents/_incident_acknowledge_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_checkbox.html
  src/argus_htmx/templates/htmx/incidents/_incident_close_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_combined_status.html
  src/argus_htmx/templates/htmx/incidents/_incident_filterbox.html
  src/argus_htmx/templates/htmx/incidents/_incident_reopen_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_status.html
  src/argus_htmx/templates/htmx/incidents/_incident_table.html
  src/argus_htmx/templates/htmx/incidents/_incident_table_row.html
  src/argus_htmx/templates/htmx/incidents/_incident_table_rows.html
  src/argus_htmx/templates/htmx/incidents/_incident_ticket.html
  src/argus_htmx/templates/htmx/incidents/_incident_ticket_edit_modal.html
  src/argus_htmx/templates/htmx/incidents/_incident_ticket_manual_create_modal.html
  src/argus_htmx/templates/htmx/incidents/_incidents_menubar.html
  src/argus_htmx/templates/htmx/incidents/_incidents_refresh_info.html
  src/argus_htmx/templates/htmx/incidents/_incidents_update_menu.html
  src/argus_htmx/templates/htmx/incidents/_selected_incidents_header.html
  src/argus_htmx/templates/htmx/incidents/incident_add_ack.html
  src/argus_htmx/templates/htmx/incidents/incident_detail.html
  src/argus_htmx/templates/htmx/incidents/incident_list.html
  src/argus_htmx/templates/htmx/themes/theme_dropdown.html
  src/argus_htmx/templates/htmx/themes/theme_list.html
  src/argus_htmx/templates/htmx/themes/themes_list.html
  src/argus_htmx/templates/htmx_base.html
  src/argus_htmx/templates/registration/login.html
Labels: discussion, lint/reformat

#195 Use old percentage syntax for log messages
  src/argus_htmx/incidents/views.py
Labels: discussion, lint/reformat

#196 Add F5, F6, F8 and F9 rules to ruff
  pyproject.toml
Labels: discussion, lint/reformat

#197 Add E4 rules to ruff
  pyproject.toml
Labels: discussion, lint/reformat

#210 Use double quotes in tags
  src/argus_htmx/templates/htmx/incidents/_base_incident_update_modal.html
Labels: lint/reformat

#166 Add support for a menu of SSO login options
  README.rst
  pyproject.toml
  src/argus_htmx/auth/__init__.py
  src/argus_htmx/auth/views.py
  src/argus_htmx/templates/registration/login.html
  src/argus_htmx/urls.py
Labels: enhancement

#204 Update README with new "How to play"-instructions
  README.rst
Labels: documentation
