Repository Uninett/argus-htmx-frontend, pull requests merged in 2024-11, with the labels that each got.

#219 Remove D018 (urlpatterns format) from ignored linter rules
  pyproject.toml
Labels: lint/reformat

#232 Fix page size fetching in incident list
  src/argus_htmx/incidents/views.py
Labels: bug

#231 Cleanup theme template naming
  src/argus_htmx/templates/htmx/base.html
  src/argus_htmx/templates/htmx/themes/_theme_dropdown.html
  src/argus_htmx/templates/htmx/themes/_theme_list.html
  src/argus_htmx/templates/htmx/themes/themes_list.html
  src/argus_htmx/themes/urls.py
  src/argus_htmx/themes/views.py
Labels: cleanup
